# Generated by Django 3.1 on 2020-09-07 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersourcetransaction',
            name='transaction_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cybersourcetransaction',
            name='transaction_reason_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13e819ae-2a45-44e4-b952-a996219901a7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cybersourcetransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('b9edea0a-e1c4-4037-8463-034e4f3505ab')),
        ),
    ]
