# Generated by Django 3.1 on 2020-09-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cybersourcetransaction',
            old_name='return_from_cybersource',
            new_name='cybersource_response_date',
        ),
        migrations.RemoveField(
            model_name='cybersourcetransaction',
            name='currency',
        ),
    ]
