"""
Django settings for payment_project project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


PROJECT_DIR = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

ROOT_DIR = os.path.dirname(PROJECT_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "*an525o6#l%^!@ckdehd+7@6^#pbspfm5-c+v_k-q=wztfgvou"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "paymentapp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "payment_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "payment_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "payment",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "localhost",
        "PORT": "5433",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

# Add these new lines
STATICFILES_DIRS = (os.path.join(PROJECT_DIR, "static"),)

STATIC_ROOT = os.path.join(ROOT_DIR, "static")
# CyberSource settings
# live details

CYBERSOURCE_PROFILE_ID = "CF7A6601-ABA2-429C-8491-BB79A814D226"
CYBERSOURCE_ACCESS_KEY = "c765a86ef1ab35e99d63b1fd801cd018"
CYBERSOURCE_SECRET_KEY = "1a7714991c574f2184f0a4b6815537927acd8ed39bec4f62990794e64af1800980a78b1f22a345229e4b8bf8dc69bd9405ebcbe659fb4afdb1c6aefa8beef1035ff7ebdadc5943f1a16a4b3d597fa22cf23882541428413db09f1b5631f7aa09db2c5a5a45164750bb5150932f9e8d8bf84cb941a0444ca38b64b35522f1d0e9"



# CYBERSOURCE_PROFILE_ID = "05D6416A-CEF6-4A92-B0DF-3736A2C702BF"
# CYBERSOURCE_ACCESS_KEY = "396b25a4cc663a7c85d4a9c012f7e561"
# CYBERSOURCE_SECRET_KEY = "e29e5f77e131420c966ecd9ce876c6dad28b237d132f481fa2b7c0168f8721dd3acc585bf7384151bd82d8fb17ac0adcacc2215843ad42858d2feba6d5ac4b0f6a470e63dab74eaab08e9d7e3a01bf560078aa8c9c104303a34650d5664e24d2be661b992fe048bca0d8a78b0ca4144cc94180fad4884c23bb7fc13b945971e1"
# CYBERSOURCE_PROFILE_ID = "22236616-9E0D-401F-B802-9E351AE92147"
# CYBERSOURCE_ACCESS_KEY = "96c15918ad783ad2bd003caa948f2ffa"
# CYBERSOURCE_SECRET_KEY = "2c1c573dff79486e83a10eb5b582f9d4f5e0da8933694ea9906848947ec7759b10922e69ac424e368b8db14d62a712b59fdde187d71844a0b90f87afe02e95b82bf5abf816864be28f2402d178cf582625dd6c6beb9942e5889d527aa498c137e6e794051ed044aa9dad73bb0d0ae35e3506f9ca39384cd6ab054730ee84211f"
CYBERSOURCE_TEST_URL = "https://testsecureacceptance.cybersource.com/pay"
# for live
CYBERSOURCE_LIVE_URL = "https://secureacceptance.cybersource.com/pay"
